/**
 * Creative Preview Data
 * Auto-generated by Ad Preview Staging Tool
 */
const CREATIVE_DATA = {
  "creativeName": "HSamuel_UK-EN_DynamicCarousel_970x250",
  "description": "",
  "clientName": "Nike",
  "createdAt": "2025-11-26T21:11:09.023Z",
  "images": [
    {
      "path": "HSamuel_UK-EN_DynamicCarousel_970x250/backup.jpg",
      "name": "backup.jpg"
    },
    {
      "path": "HSamuel_UK-EN_DynamicCarousel_970x250/images/logo.svg",
      "name": "logo.svg"
    }
  ],
  "files": [
    {
      "path": "HSamuel_UK-EN_DynamicCarousel_970x250/atd-css-library.css",
      "type": "css"
    },
    {
      "path": "HSamuel_UK-EN_DynamicCarousel_970x250/atd-js-library.js",
      "type": "javascript"
    },
    {
      "path": "HSamuel_UK-EN_DynamicCarousel_970x250/atd-main.css",
      "type": "css"
    },
    {
      "path": "HSamuel_UK-EN_DynamicCarousel_970x250/atd-main.js",
      "type": "javascript"
    },
    {
      "path": "HSamuel_UK-EN_DynamicCarousel_970x250/backup.jpg",
      "type": "image"
    },
    {
      "path": "HSamuel_UK-EN_DynamicCarousel_970x250/fonts/campton_light-webfont.woff",
      "type": "font"
    },
    {
      "path": "HSamuel_UK-EN_DynamicCarousel_970x250/fonts/campton_light-webfont.woff2",
      "type": "font"
    },
    {
      "path": "HSamuel_UK-EN_DynamicCarousel_970x250/fonts/campton_semibold-webfont.woff",
      "type": "font"
    },
    {
      "path": "HSamuel_UK-EN_DynamicCarousel_970x250/fonts/campton_semibold-webfont.woff2",
      "type": "font"
    },
    {
      "path": "HSamuel_UK-EN_DynamicCarousel_970x250/images/logo.svg",
      "type": "image"
    },
    {
      "path": "HSamuel_UK-EN_DynamicCarousel_970x250/index.html",
      "type": "html"
    }
  ]
};

// Export for module environments
if (typeof module !== 'undefined' && module.exports) {
  module.exports = CREATIVE_DATA;
}
