/**
 * Creative Preview Data
 * Auto-generated by Ad Preview Staging Tool
 */
const CREATIVE_DATA = {
  "creativeName": "flyeralarm_fa23_new_remarketing_creatives_320x160_fr",
  "description": "",
  "clientName": "Google",
  "createdAt": "2025-11-26T20:58:53.137Z",
  "images": [
    {
      "path": "flyeralarm_fa23_new_remarketing_creatives_320x160_fr/320x160/backup.jpg",
      "name": "backup.jpg"
    },
    {
      "path": "flyeralarm_fa23_new_remarketing_creatives_320x160_fr/320x160/images/logo-image.svg",
      "name": "logo-image.svg"
    },
    {
      "path": "flyeralarm_fa23_new_remarketing_creatives_320x160_fr/320x160/images/logo-image_rd.svg",
      "name": "logo-image_rd.svg"
    },
    {
      "path": "flyeralarm_fa23_new_remarketing_creatives_320x160_fr/320x160/images/logo-subheadline.svg",
      "name": "logo-subheadline.svg"
    },
    {
      "path": "flyeralarm_fa23_new_remarketing_creatives_320x160_fr/320x160/images/logo-subheadline_rd.svg",
      "name": "logo-subheadline_rd.svg"
    }
  ],
  "files": [
    {
      "path": "flyeralarm_fa23_new_remarketing_creatives_320x160_fr/320x160/backup.jpg",
      "type": "image"
    },
    {
      "path": "flyeralarm_fa23_new_remarketing_creatives_320x160_fr/320x160/gsap/gsap.min.js",
      "type": "javascript"
    },
    {
      "path": "flyeralarm_fa23_new_remarketing_creatives_320x160_fr/320x160/gsap/SplitText.min.js",
      "type": "javascript"
    },
    {
      "path": "flyeralarm_fa23_new_remarketing_creatives_320x160_fr/320x160/images/logo-image.svg",
      "type": "image"
    },
    {
      "path": "flyeralarm_fa23_new_remarketing_creatives_320x160_fr/320x160/images/logo-image_rd.svg",
      "type": "image"
    },
    {
      "path": "flyeralarm_fa23_new_remarketing_creatives_320x160_fr/320x160/images/logo-subheadline.svg",
      "type": "image"
    },
    {
      "path": "flyeralarm_fa23_new_remarketing_creatives_320x160_fr/320x160/images/logo-subheadline_rd.svg",
      "type": "image"
    },
    {
      "path": "flyeralarm_fa23_new_remarketing_creatives_320x160_fr/320x160/index.html",
      "type": "html"
    },
    {
      "path": "flyeralarm_fa23_new_remarketing_creatives_320x160_fr/320x160/script.js",
      "type": "javascript"
    },
    {
      "path": "flyeralarm_fa23_new_remarketing_creatives_320x160_fr/320x160/style.css",
      "type": "css"
    },
    {
      "path": "flyeralarm_fa23_new_remarketing_creatives_320x160_fr/320x160/textFit.min.js",
      "type": "javascript"
    }
  ]
};

// Export for module environments
if (typeof module !== 'undefined' && module.exports) {
  module.exports = CREATIVE_DATA;
}
