/**
 * Creative Preview Data
 * Auto-generated by Ad Preview Staging Tool
 */
const CREATIVE_DATA = {
  "creativeName": "ernest_jones_gift_finder_studio_970x250",
  "description": "",
  "clientName": "Meta",
  "createdAt": "2025-11-26T21:44:31.148Z",
  "images": [
    {
      "path": "ernest_jones_gift_finder_studio_970x250/970x250/backup.jpg",
      "name": "backup.jpg"
    },
    {
      "path": "ernest_jones_gift_finder_studio_970x250/970x250/images/arrow.svg",
      "name": "arrow.svg"
    },
    {
      "path": "ernest_jones_gift_finder_studio_970x250/970x250/images/ej-logo.svg",
      "name": "ej-logo.svg"
    }
  ],
  "files": [
    {
      "path": "ernest_jones_gift_finder_studio_970x250/970x250/backup.jpg",
      "type": "image"
    },
    {
      "path": "ernest_jones_gift_finder_studio_970x250/970x250/fonts/Oxygen-Bold.woff2",
      "type": "font"
    },
    {
      "path": "ernest_jones_gift_finder_studio_970x250/970x250/fonts/Oxygen-Regular.woff2",
      "type": "font"
    },
    {
      "path": "ernest_jones_gift_finder_studio_970x250/970x250/gsap/gsap.min.js",
      "type": "javascript"
    },
    {
      "path": "ernest_jones_gift_finder_studio_970x250/970x250/images/arrow.svg",
      "type": "image"
    },
    {
      "path": "ernest_jones_gift_finder_studio_970x250/970x250/images/ej-logo.svg",
      "type": "image"
    },
    {
      "path": "ernest_jones_gift_finder_studio_970x250/970x250/index.html",
      "type": "html"
    },
    {
      "path": "ernest_jones_gift_finder_studio_970x250/970x250/script.js",
      "type": "javascript"
    },
    {
      "path": "ernest_jones_gift_finder_studio_970x250/970x250/style.css",
      "type": "css"
    }
  ]
};

// Export for module environments
if (typeof module !== 'undefined' && module.exports) {
  module.exports = CREATIVE_DATA;
}
