/**
 * Creative Preview Data
 * Auto-generated by Ad Preview Staging Tool
 */
const CREATIVE_DATA = {
  "creativeName": "BarbaraSturm_UK-EN_DynamicCarousel_160x600",
  "description": "",
  "clientName": "Verizon",
  "createdAt": "2025-11-26T20:47:49.561Z",
  "images": [
    {
      "path": "BarbaraSturm_UK-EN_DynamicCarousel_160x600/backup.jpg",
      "name": "backup.jpg"
    },
    {
      "path": "BarbaraSturm_UK-EN_DynamicCarousel_160x600/images/logo.svg",
      "name": "logo.svg"
    },
    {
      "path": "BarbaraSturm_UK-EN_DynamicCarousel_160x600/images/spinner.svg",
      "name": "spinner.svg"
    }
  ],
  "files": [
    {
      "path": "BarbaraSturm_UK-EN_DynamicCarousel_160x600/atd-css-library.css",
      "type": "css"
    },
    {
      "path": "BarbaraSturm_UK-EN_DynamicCarousel_160x600/atd-js-library.js",
      "type": "javascript"
    },
    {
      "path": "BarbaraSturm_UK-EN_DynamicCarousel_160x600/atd-main.css",
      "type": "css"
    },
    {
      "path": "BarbaraSturm_UK-EN_DynamicCarousel_160x600/atd-main.js",
      "type": "javascript"
    },
    {
      "path": "BarbaraSturm_UK-EN_DynamicCarousel_160x600/backup.jpg",
      "type": "image"
    },
    {
      "path": "BarbaraSturm_UK-EN_DynamicCarousel_160x600/fonts/Europa-Bold.woff",
      "type": "font"
    },
    {
      "path": "BarbaraSturm_UK-EN_DynamicCarousel_160x600/fonts/Europa-Bold.woff2",
      "type": "font"
    },
    {
      "path": "BarbaraSturm_UK-EN_DynamicCarousel_160x600/fonts/Europa-Light.woff",
      "type": "font"
    },
    {
      "path": "BarbaraSturm_UK-EN_DynamicCarousel_160x600/fonts/Europa-Light.woff2",
      "type": "font"
    },
    {
      "path": "BarbaraSturm_UK-EN_DynamicCarousel_160x600/fonts/Europa-Regular.woff",
      "type": "font"
    },
    {
      "path": "BarbaraSturm_UK-EN_DynamicCarousel_160x600/fonts/Europa-Regular.woff2",
      "type": "font"
    },
    {
      "path": "BarbaraSturm_UK-EN_DynamicCarousel_160x600/images/logo.svg",
      "type": "image"
    },
    {
      "path": "BarbaraSturm_UK-EN_DynamicCarousel_160x600/images/spinner.svg",
      "type": "image"
    },
    {
      "path": "BarbaraSturm_UK-EN_DynamicCarousel_160x600/index.html",
      "type": "html"
    }
  ]
};

// Export for module environments
if (typeof module !== 'undefined' && module.exports) {
  module.exports = CREATIVE_DATA;
}
